services:
  payment_api:
    image: immoltex/payment_api:latest
    ports:
      - "8080:8080"
    networks:
      - backend

  pricer:
    image: immoltex/pricer:latest
    ports:
      - "8083:8083"
    networks:
      - backend

  crypto_manager:
    image: immoltex/crypto_manager:latest
    ports:
      - "8082:8082"
    networks:
      - backend

  tx_service:
    image: immoltex/tx_service:latest
    ports:
      - "9090:9090"
    networks:
      - backend

networks:
  backend: