CREATE TABLE "crypto_payments" (
                                   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "crypto_wallet_id" integer,
                                   "status" integer,
                                   "amount_crypto" float,
                                   "merchant_id" varchar(50),
                                   "request_id" varchar(50),
                                   "amount_fiat" float,
                                   "currency_fiat" varchar(30)
);

ALTER TABLE "crypto_payments" ADD FOREIGN KEY ("crypto_wallet_id") REFERENCES "crypto_wallets" ("id");

ALTER TABLE crypto_wallets DROP COLUMN amount_crypto;
